name: Ubuntu

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        [[ -r dependencies/apt.txt ]] && sed 's/#.*//' dependencies/apt.txt | xargs sudo apt-get install -y

    - name: Configure
      run: CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} cmake -DENABLE_CONAN=OFF -Bbuild

    - name: Build
      run: cmake --build build
